### ISSUE TITLE
Display not quite working right

### ISSUE THREAD

**Issue by entozoon** [holzachr/MS6205-arduino-library#2]
Hi there, first of all what you've made here is fantastic! I can't tell you how helpful it's been so far - all the diagrams in particular!

I've recreated your wiring with an MC6205 (although I believe it's exactly the same as MS6205) and it's aaaalmost working. I was hoping you might have a clue as to what's going wrong. Could be anything, and I'm a little out of ideas :(

Code snippet:
```cpp
display.setCursor(0, 0);
display.write("A");
delay(1000);
display.setCursor(1, 1);
display.write("B");
delay(1000);
display.setCursor(2, 2);
display.write("C");
delay(1000);
display.setCursor(3, 3);
display.write("D");
delay(1000);
display.setCursor(4, 4);
display.write("E");
delay(1000);
display.setCursor(5, 5);
display.write("F");
delay(1000);
display.setCursor(6, 6);
display.write("G");
delay(1000);
display.setCursor(7, 7);
display.write("H");
delay(1000);
display.setCursor(8, 8);
display.write("I");
delay(1000);
display.setCursor(9, 9);
display.write("J");
delay(1000);
```

Expected display output
```
A
 B
  C
   D
    E
     F
      G
       H
        I
         J
```

Actual output (same every time):
![photo](https://i.imgur.com/PVmWVTM.jpeg)

Any clue dude? Perhaps I've done something wrong with the shift register..?

PS: Did you use some software to draw the text diagrams, or just by hand? Either way, fantastic work thanks again.

**Comment by entozoon** [comment]
Ah! I think I fixed it! With a combination of a few things, not sure exactly which:
- Faulty shift register chip
- Slight misconnections in breadboard
- USB power through ESP8266 not being quite enough, compared to external 5V supply for everything (including shift reg)

Sorry to bother you. Sometimes in asking a question it helps us figure out the answer ourselves :)

**Comment by holzachr** [comment]
Hey buddy,

I'm glad you fixed it! And of coure I'm happy to see that someone is eventually using my library...

The diagrams were painted using asciiflow.com - really great stuff they are doing there.

Whenever you're done with your project and feel like you'd like to upload some fancy pictures, please feel free :-)

**Comment by entozoon** [comment]
@holzachr I finished my project!
https://www.michaelcook.tech/plasma-display-mc6205/

Loved making it, and wouldn't have managed it at all without the help of this lib so thank you very much!
The only thing I couldn't figure out unfortunately was how to remove all the horizontal lines. I believe it is possible, based on a few photographs I found randomly where it appears they cut some resistors out:
http://sim.loa.su/pub/_hardware/MC6205/MC6205.jpg
http://sim.loa.su/pub/_hardware/MC6205/MC6205-cut-___.jpg
The internals of my model isn't similar enough for me to just start snipping and find out :(

**Comment by holzachr** [comment]
Hey Michael,
happy to see it worked out for you, and finally looks _that_ nice. Is that wooden case laser cut?
Also thank you for the hint about getting rid of those lines by cutting the resistors. Maybe I'll give that one a try one day...

Unfortunately my MC6250 (used for weather forecast) gave up after about half a year of service, showing increasing random distortion over time, even without any controller attached. 
One could probably dig down to a certain faulty IC, find a functional western substitution for it, fiddle some connection adapter negating some control lines... But not me ;-)
Hope you may enjoy yours much longer!

**Comment by entozoon** [comment]
@holzachr It is indeed laser cut. 
Such a shame your screen deteriorated. I suppose they do eventually, but that sucks.

Perhaps consider grabbing another 'new old stock' one, while they're around. I bought this - https://www.ebay.co.uk/itm/1-x-Elektronika-MS6205-NEW-NOS-Nixie-matrix-screen-MC6205-factory-box/313399446006?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649
